apiVersion: 1

datasources:
  - name: Superbrain
    type: postgres
    uid: superbrain-pg
    url: postgres:5432
    user: superbrain
    secureJsonData:
      password: superbrain
    jsonData:
      database: superbrain
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
