"""Add topics and article_topic_matches tables

Revision ID: b2d65e7d401c
Revises: 004
Create Date: 2026-05-07 07:56:55.584758
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2d65e7d401c'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_topics_name_version')
    )
    op.create_table('article_topic_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('topic_version', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'topic_id', name='uq_match_article_topic')
    )
    op.create_index(op.f('ix_article_topic_matches_article_id'), 'article_topic_matches', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_topic_matches_topic_id'), 'article_topic_matches', ['topic_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_article_topic_matches_topic_id'), table_name='article_topic_matches')
    op.drop_index(op.f('ix_article_topic_matches_article_id'), table_name='article_topic_matches')
    op.drop_table('article_topic_matches')
    op.drop_table('topics')
